server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mais}
    username: ${DB_USER:mais_user}
    password: ${DB_PASS:mais_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret: ${JWT_SECRET:change_me_change_me_change_me_change_me}
